### ISSUE TITLE
Enumerated bullets are not handled

### ISSUE THREAD

**Issue by vonguard** [erikh/gdocs-export#16]
This doc https://docs.google.com/document/d/13LZMbVXF4-pdbADWtEg2dGZCKcWhzFgyBYwxMr48NXE/edit Has split enumerated bullet points with images in between them. The converted doc came out without images (or tags) and the enumerated bullets were just black bullets.

**Comment by erikh** [comment]
I think this is now resolved as of #20, but the images in that document are not being presented appropriately still I don't think; instead being appended to the end of the content.

This is because, semantically they are not a part of the "bullet item". I'm not quite sure how to resolve this yet. Any idea how we might structure the document differently?

**Comment by erikh** [comment]
see #22
